### PR TITLE
Refactor IMAP Connection and Message

### PR DESCRIPTION
**Pull request by stanhu**
Refactor IMAP classes into MailRoom::IMAP structure

MailRoom::Connection (base)
MailRoom::Message (base)
MailRoom::IMAP::Connection < MailRoom::Connection
MailRoom::IMAP::Message < MailRoom::Message

Future connection/message types would be:

MailRoom::XXX::Connection
MailRoom::XXX::Message

This is in preparation for supporting other mail inputs, such as Microsoft Graph API. OAuth2 with service accounts only works with the Microsoft Graph API, not with IMAP.

This is the first step towards supporting https://github.com/tpitale/mail_room/issues/113.

### CODE REVIEW

**Comment by tpitale** [comment]
I think I'd prefer if this were like this:

MailRoom::Connection (base)
MailRoom::Message (base)
MailRoom::IMAP::Connection < MailRoom::Connection
MailRoom::IMAP::Message < MailRoom::Message

Future connection/message types would be:

MailRoom::XXX::Connection
MailRoom::XXX::Message

**Comment by stanhu** [comment]
> I think I'd prefer if this were like this:
> 
> MailRoom::Connection (base)
> MailRoom::Message (base)
> MailRoom::IMAP::Connection < MailRoom::Connection
> MailRoom::IMAP::Message < MailRoom::Message
> 
> Future connection/message types would be:
> 
> MailRoom::XXX::Connection
> MailRoom::XXX::Message

Yeah, that's better. Updated.

**Review by tpitale — APPROVED** [review]

**Comment by tpitale** [comment]
@stanhu Let me know when you'd like me to merge this.

**Comment by stanhu** [comment]
@tpitale Ready to merge!

**Pull request merged**
