### PR TITLE
Don't override original idle method for Net::IMAP

### PR DESCRIPTION
**Pull request by godfat**
So that we take advantage of future official code

Thanks!

### CODE REVIEW

**Comment by tpitale** [comment]
I'm aware of the tradeoffs.

**Comment by tpitale** [comment]
I may accept a PR to check for RUBY_VERSION less than 2.3. As it should be clear, this is a backport for what amounts to a bug in Ruby for those versions.

**Comment by godfat** [comment]
Cool, thanks. I'll stop here since I am not sure if checking RUBY_VERSION is a good idea.

**Comment by tpitale** [comment]
Thanks, I partitioned it as much as possible, should not impact any other use of net/IMAP.

**Pull request closed without merging**
