### PR TITLE
Pass ssl options from mailbox config

### LINKED ISSUE #47: It's not possible to run mail_room over SSL, even if the host is localhost
```
/usr/local/lib/ruby/2.1.0/openssl/ssl.rb:240:in `post_connection_check': hostname "localhost" does not match the server certificate (OpenSSL::SSL::SSLError)
        from /usr/local/lib/ruby/2.1.0/net/imap.rb:1456:in `start_tls_session'
        from /usr/local/lib/ruby/2.1.0/net/imap.rb:1047:in `initialize'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:20:in `new'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:20:in `imap'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:88:in `log_in'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:69:in `setup'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/mailbox_watcher.rb:132:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/coordinator.rb:19:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/coordinator.rb:19:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/lib/mail_room/cli.rb:52:in `start'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail_room-0.5.2/bin/mail_room:5:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/mail_room:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/mail_room:23:in `<main>'
```

### PR DESCRIPTION
**Pull request by tpitale**
Also: replace verify_mode with SSL constant

Resolves #47

### CODE REVIEW

**Comment by tpitale** [comment]
@sixtyfive Can you try this out. I updated the README, let me know if it needs more details.

**Comment by tpitale** [comment]
@sixtyfive Have you been able to test this?

**Comment by sixtyfive** [comment]
Sorry, I'm on a deadline until tonight and have only had 4 hours of sleep for the last couple of nights. I'll try to test it tomorrow evening!

**Comment by tpitale** [comment]
No worries. Just hadn't heard anything. No rush. Just wanted to make sure you saw it.

**Comment by tpitale** [comment]
Hey @sixtyfive. Hoping you can take a look at this. Or, let me know and I'll close until you're available.

**Comment by sixtyfive** [comment]
Hey there, thanks for reminding me again! I'll take a look now.

**Comment by sixtyfive** [comment]
Hmm, first about the `README` ... can't find anything in there about this. Am I looking in the right place? (https://github.com/tpitale/mail_room/blob/master/README.md)

**Comment by tpitale** [comment]
Yes, check the files on the PR: https://github.com/tpitale/mail_room/pull/48/files I haven't merged this yet, so it won't be in master.

**Comment by sixtyfive** [comment]
Okay, found it. The paragraph reads clearly enough and I think it should be fine. One thing that would not be clear to me if I'd never seen YAML before was whether I need to put the `:none` into any sort of quotation signs.

As for the functionality itself, I tried to get it to work, but my skills don't seem to be advanced enough to do that. How do you get the version with the PR installed through Gemfile?

**Comment by tpitale** [comment]
```ruby
gem 'mail_room', github: 'tpitale/mail_room', branch: 'ssl-options'
```

**Comment by tpitale** [comment]
```yaml
:ssl:
  :verify_mode: :none
```

**Comment by sixtyfive** [comment]
Okay, after some fighting with GitLab's locked Gemfile, I got it working now:

```
    :host: localhost
    :port: 993
    :ssl:
      :verify_mode: :none
```

Sorry this took so long!

**Pull request merged**
