### PR TITLE
Update gitlab-ci to reflect new ruby versions

### PR DESCRIPTION
**Pull request by cablett**
Hi @tpitale ! Hope you and yours are safe and well.

I noticed the ruby versions, etc in the `gitlab-ci.yml` were out of date, so here's a change that will bring them more up to date 🙂 The version here works with the current GitLab CI engine as of this writing.

What do you think?

### CODE REVIEW

**Comment by tpitale** [comment]
Looks good. I haven’t kept up with which rubies are supported anymore. Is 2.3 end of life?

**Comment by cablett** [comment]
You're right, [it is no longer supported](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/)

**Comment by cablett** [comment]
and [2.4 for that matter!](https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/) 😆

**Comment by cablett** [comment]
Thanks for your patience @tpitale - I've updated the file to include 2.5-2.7.

**Comment by tpitale** [comment]
Thanks @cablett !

**Pull request merged**
