### PR TITLE
Rough out starttls support

### LINKED ISSUE #41: StartTLS support
I'm not a ruby guy so I can't implement this myself (but it seems the change would be primitive). My mail server only supports StartTLS (it doesn't acceppt non-encrypted connections and 993 is closed). So to connect to it, the `STARTTLS` upgrade needs to be performed.

From what I gather, `Net::IMAP#starttls` is a simple command to execute after connecting so it would be cool to have an option to trigger this once the connection is established.

### PR DESCRIPTION
**Pull request by tpitale**
* add `start_tls` to mailbox config
* run `starttls` on mailbox before calling login (not sure if this is the right place)

Resolves #41

### CODE REVIEW

**Comment by tpitale** [comment]
@Javex @DouweM if you have some way to test this out … that would be awesome.

**Comment by Javex** [comment]
I tested this against my own mail server. It _seemed_ to work, I was just not capable of configuring a delivery method -.- Nonetheless, adding a `puts "."` after the `idle` line gave me output when a mail arrived. Since the StartTLS thing shouldn't be interferring at this point it's probably just me being incapable of running your tool... :<

I would recommend a minor cosmetic change and call the option `starttls` to be consistent with all the places StartTLS does not get any spaces.

Conerning the `verify` option: I guess that would be a completely different issue as this would also apply to SSL. If this is needed or at some point created it should just be correctly applied in both cases.

**Comment by tpitale** [comment]
I originally had it as starttls … but I think it was error prone in typing the two 't' together. So I switched it to use the underscore.

**Comment by tpitale** [comment]
Released 0.5.2.

**Pull request merged**
