### PR TITLE
GitLab redis config

### PR DESCRIPTION
**Pull request by cablett**
Hi again @tpitale 👋 

This PR modifies the Redis config to be a bit more compatible with GitLab CI.

I hope you don't mind that I've separated out some of this config into multiple PRs (please let me know if you'd prefer 1 big PR). 🙂 

Please let me know what you think.

### CODE REVIEW

**Comment by tpitale** [comment]
🤔 Despite what Travis CI is saying … this is failing on every version, not because of this code, but because of one of the testing libraries. 🤦

**Comment by tpitale** [comment]
Oh this is the bourne/mocha thing. Yeah, I think we need to rip them out first.

**Comment by tpitale** [comment]
Can you merge or rebase this off master. I’d love to see if Travis passes.

**Comment by cablett** [comment]
Done! 🤞

**Comment by cablett** [comment]
It passes! 🎉 Does it look good to you @tpitale ? If so, please merge 🙂

**Comment by cablett** [comment]
Ugh, some commits snuck in there again. 🤦 Let me fix

**Comment by cablett** [comment]
Much better. Apologies for the noise. 🙇

**Pull request merged**
