### PR TITLE
charlock_holmes is a runtime dependency

### PR DESCRIPTION
**Pull request by DouweM**

### CODE REVIEW

**Comment by tpitale** [comment]
It's only a dependency if you use the redis/sidekiq stuff. There's no good way to manage those sorts of dependencies that only _some_ folks need. There are other dependencies for things like que, letter_opener, etc that we don't have in the gemspec.

**Comment by DouweM** [comment]
Ah, right you are!

**Comment by tpitale** [comment]
@DouweM maybe we should add more clarification in the readme? If you think that'll help I'll add that.

**Comment by DouweM** [comment]
@tpitale I think that would be useful. It wasn't actually causing any issues for us since we had `charlock_holmes` in the bundle anyway, but it surprised me when I saw the `development_dependency`.

**Pull request closed without merging**
