### PR TITLE
fix postback username and password to delivery_username and delivery_…

### PR DESCRIPTION
**Pull request by clairton**
…password as doc

### CODE REVIEW

**Comment by tpitale** [comment]
@clairton Would you mind also fixing the README? It should have been `username`. That's my fault.

**Comment by clairton** [comment]
At the doc `delivery_username` and in code `username`, with this PR works with two. What is correct?

**Comment by tpitale** [comment]
Since it has been published already as `delivery_username` the code needs to support it, which you've done. This way the _code_ will work regardless of the case.

But, the docs in README _should_ say `username` and `password`.

**Comment by clairton** [comment]
Hi @tpitale, done =)

**Review by tpitale — APPROVED** [review]

**Comment by tpitale** [comment]
Thank you!

**Review by abood640 — APPROVED** [review]

**Pull request merged**
